version: '3.8'

services:
  fastapi:
    build: .
    volumes:
      - ./qr_codes_storage:/myapp/qr_codes_storage # Maps ./qr_codes from your host to /myapp/qr_codes in the container
      - ./:/myapp/
    environment:
      - QR_STORAGE_DIRECTORY=./qr_codes_storage
      - PRIMARY_COLOR=red
      - BACKGROUND_COLOR=white
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./qr_codes_storage:/var/www/qr_codes_storage # Maps ./qr_codes from your host to /var/www/qr_codes in the container